<?php
return array(
            '_electro_pc'=>'бортовой компьютер',
            '_mus_cd'=>'CD проигрыватель',
            '_clim_comdition'=>'кондиционер',
            '_clim_climate'=>'климат-контроль',
            '_secure_imob'=>'иммобилайзер',
            '_secure_oralka'=>'сигнализация',
            '_secure_central_lock'=>'центральный замок',
            '_electro_window'=>'электростеклоподъёмник',
            '_electro_mirrors'=>'электрозеркала',
            '_electro_cruise'=>'круиз-контроль',
            '_electro_chair'=>'электро сиденья',
            '_electro_hot_chair'=>'подогрев сидений ',
            '_electro_hot_mirrors'=>'подогрев зеркал',
            '_electro_checker_distance'=>'парктроник',
            '_electro_gyr'=>'гидроусилитель',
            '_stab_abs'=>'ABS',
            '_secure_buks'=>'буксировочный крюк',
            '_dop_salon_koza'=>'салон кожаный',
            '_dop_salon_trapka'=>'салон велюр',
            '_dop_good_weel'=>'литые диски',
            '_dop_roof_door'=>'люк',
            '_lights_xenon'=>'ксенон',
            '_lights_nofog'=>'противотуманки',
            '_airbag_front1'=>'передняя подушка безопасности водителя',
            '_airbag_front2'=>'передняя подушка безопасности пассажира',
            '_airbag_lr'=>'боковые подушки безопасности',
            '_airbag_window'=>'оконные подушки безопасности',
);